version: "3"

services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic 
    volumes:
      - db-data:/var/lib/postgresql/data

  spring-petclinic:
    image: test_spring:latest
    ports:
      - "8080:8080"

volumes:
  db-data:
