apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      type: database
      env: dev
  
  template:
    metadata:
      name: db-pod
      labels:
        type: database
        env: dev
    spec:
      containers:
        - name: db-container
          image: postgres:14.1
          ports:
            - containerPort: 5432
          env: 
            - name: "POSTGRES_PASSWORD"
              value: "petclinic"
              
            - name: "POSTGRES_USER"
              value: "petclinic"

            - name: "POSTGRES_DB"
              value: "petclinic"
        